# Generated by Django 5.2.8 on 2025-11-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorygame',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='best_score',
            field=models.IntegerField(default=0),
        ),
    ]
