# Generated by Django 5.2.8 on 2025-11-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_memorygame_score_player_best_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
