# Generated by Django 5.2.8 on 2025-11-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0003_player_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
